name: Build and Push Docker Images

on:
  schedule:
    - cron: '45 1 * * *'
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        subfolder: ['build-package', 'test-package', 'publish-package', 'update-package-via-manifest']

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container images/tags
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.subfolder }}
          push: true
          tags: ghcr.io/brenekh/auto-aur-${{ matrix.subfolder }}:latest
