name: Build, Test, and Lint Rust Code

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-D warnings"

# TODO: Figure out how to install libalpm headers required for Paru bindgen
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
      with:
        # Allow cache to be shared between jobs
        add-job-id-key: "false"
        add-rust-environment-hash-key: "false"

    - name: Build All Binary Crates
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
      with:
        # Allow cache to be shared between jobs
        add-job-id-key: "false"
        add-rust-environment-hash-key: "false"

    - name: Test All Workspace Crates
      run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: Swatinem/rust-cache@v2
      with:
        # Allow cache to be shared between jobs
        add-job-id-key: "false"
        add-rust-environment-hash-key: "false"

    - name: Lint All Workspace Crates
      run: cargo clippy
